development:
  port: 9312
  morphology: stem_ru
  enable_star: true
  min_infix_len: 3
production:
  port: 9313
  morphology: stem_ru
  enable_star: true
  min_infix_len: 3
  bin_path: '/usr/local/bin'